SELECT * FROM EMPLEADOS;
SELECT * FROM ISAPRES;
SELECT * FROM SUCURSALES;
SELECT * FROM COMUNAS;
SELECT * FROM VENTAS;
SELECT * FROM DETALLE_VENTAS;
SELECT * FROM REPORTE_SUELDOS;
SELECT * FROM CARGOS;
SELECT * FROM AFPS;
--1
SELECT ROUND(PRECIO_UNITARIO*CANTIDAD*(1-DESCUENTO)*0.19) "IVA" FROM DETALLE_VENTAS;
DECLARE
 CURSOR cr_iva IS
   SELECT IVA FROM DETALLE_VENTAS
   FOR UPDATE;
BEGIN
   FOR reg_datos IN cr_iva
   LOOP
   UPDATE DETALLE_VENTAS
   SET IVA=ROUND(PRECIO_UNITARIO*CANTIDAD*(1-DESCUENTO)*0.19) ;
   END LOOP;
END;

--2

DECLARE
 CURSOR cr_reporte IS
  SELECT e.EMPLEADO_ID "IDEMPLEADO",EXTRACT(YEAR FROM v.FECHA)"AÑO",EXTRACT(MONTH FROM v.FECHA) "MES",
  DECODE(c.COMUNA,'Viña del Mar',ROUND(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)*0.02))
  ,'Las Condes',ROUND(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)*0.03))
  ,'Santiago',ROUND(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)*0.018))) "COMISION"
  FROM EMPLEADOS e
  JOIN VENTAS v ON(e.EMPLEADO_ID=v.VENDEDOR_ID)
  JOIN DETALLE_VENTAS d ON (v.VENTA_ID=d.VENTA_ID)
  JOIN SUCURSALES s ON(v.SUCURSAL_ID=s.SUCURSAL_ID)
  JOIN COMUNAS c ON(s.COMUNA_ID=c.COMUNA_ID)
  GROUP BY e.EMPLEADO_ID,EXTRACT(YEAR FROM v.FECHA),EXTRACT(MONTH FROM v.FECHA),c.COMUNA
  ORDER BY EMPLEADO_ID;
BEGIN
 FOR reg_datos IN cr_reporte
 LOOP
  INSERT INTO REPORTE_SUELDOS(EMPLEADO_ID,ANNO,MES,COMISION)
  VALUES(reg_datos.idempleado,reg_datos.año,reg_datos.mes,reg_datos.comision);
 END LOOP;
END;

SELECT * FROM REPORTE_SUELDOS;

--3
SELECT EMPLEADO_ID FROM EMPLEADOS;

SELECT e.EMPLEADO_ID "IDEMPLEADO",EXTRACT(YEAR FROM v.FECHA)"AÑO",EXTRACT(MONTH FROM v.FECHA) "MES",
  DECODE(c.COMUNA,'Viña del Mar',ROUND(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)*0.02))
  ,'Las Condes',ROUND(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)*0.03))
  ,'Santiago',ROUND(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)*0.018))) "COMISION",
  e.SUELDO_BASE,e.SUELDO_BASE*0.25 "GRATIFICACION",
  e.SUELDO_BASE+e.SUELDO_BASE*0.25+DECODE(c.COMUNA,'Viña del Mar',ROUND(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)*0.02))
  ,'Las Condes',ROUND(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)*0.03))
  ,'Santiago',ROUND(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)*0.018)))"BASE IMPONIBLE"
  FROM EMPLEADOS e
  JOIN VENTAS v ON(e.EMPLEADO_ID=v.VENDEDOR_ID)
  JOIN DETALLE_VENTAS d ON (v.VENTA_ID=d.VENTA_ID)
  JOIN SUCURSALES s ON(v.SUCURSAL_ID=s.SUCURSAL_ID)
  JOIN COMUNAS c ON(s.COMUNA_ID=c.COMUNA_ID)
  JOIN ISAPRES i ON(i.ISAPRE_ID=e.ISAPRE_ID)
  GROUP BY e.EMPLEADO_ID,EXTRACT(YEAR FROM v.FECHA),EXTRACT(MONTH FROM v.FECHA),c.COMUNA,
  e.SUELDO_BASE
  ORDER BY EMPLEADO_ID;
  
  DECLARE
  BEGIN
  END;