
SELECT * FROM EMPLEADOS;
SELECT * FROM ISAPRES;
SELECT * FROM SUCURSALES;
SELECT * FROM COMUNAS;
SELECT * FROM VENTAS;
SELECT * FROM DETALLE_VENTAS;
SELECT * FROM REPORTE_SUELDOS;
SELECT * FROM CARGOS;
SELECT * FROM AFPS;

SELECT e.EMPLEADO_ID "IDEMPLEADO",c.COMUNA
  FROM EMPLEADOS e
  LEFT OUTER JOIN VENTAS v ON(e.EMPLEADO_ID=v.VENDEDOR_ID)
  LEFT OUTER JOIN DETALLE_VENTAS d ON (v.VENTA_ID=d.VENTA_ID)
  LEFT OUTER JOIN SUCURSALES s ON(v.SUCURSAL_ID=s.SUCURSAL_ID)
  LEFT OUTER JOIN COMUNAS c ON(s.COMUNA_ID=c.COMUNA_ID)
  JOIN ISAPRES i ON(i.ISAPRE_ID=e.ISAPRE_ID)
  GROUP BY e.EMPLEADO_ID,c.COMUNA,
  e.SUELDO_BASE
  ORDER BY EMPLEADO_ID;
  
CREATE OR REPLACE PROCEDURE gratificacion(sueldo IN INT,total OUT INT)
IS
BEGIN
total := sueldo * 0.25;
DBMS_OUTPUT.PUT_LINE(total);
END gratificacion;

CREATE OR REPLACE PROCEDURE comision(sueldo IN INT,comuna IN INT,total OUT INT)
IS
BEGIN
CASE comuna WHEN 1 THEN total:=sueldo*0.03;
            WHEN 2 THEN total:=sueldo*0.02;
            WHEN 3 THEN total:=sueldo*0.018;
            ELSE total:=sueldo*1;
END CASE;
total:=sueldo*porcentaje;
END comision;

DECLARE
CURSOR cr_reporte IS
SELECT e.EMPLEADO_ID "IDEMPLEADO",e.SUELDO_BASE "SUELDO",NVL(c.COMUNA_ID,0) "COMUNA_ID"
  FROM EMPLEADOS e
  LEFT OUTER JOIN VENTAS v ON(e.EMPLEADO_ID=v.VENDEDOR_ID)
  LEFT OUTER JOIN DETALLE_VENTAS d ON (v.VENTA_ID=d.VENTA_ID)
  LEFT OUTER JOIN SUCURSALES s ON(v.SUCURSAL_ID=s.SUCURSAL_ID)
  LEFT OUTER JOIN COMUNAS c ON(s.COMUNA_ID=c.COMUNA_ID)
  JOIN ISAPRES i ON(i.ISAPRE_ID=e.ISAPRE_ID)
  GROUP BY e.EMPLEADO_ID,
  e.SUELDO_BASE,c.COMUNA_ID
  ORDER BY EMPLEADO_ID;
  v_total NUMBER(8);
BEGIN
FOR reg_datos IN cr_reporte
LOOP
comision(reg_datos.sueldo,reg_datos.comuna_id,v_total);
DBMS_OUTPUT.PUT_LINE(v_total);
END LOOP;
END;
