SELECT MIN(SALARY),MAX(SALARY),SUM(SALARY),ROUND(AVG(SALARY)),COUNT(*) FROM EMPLOYEES;
DECLARE
 V_MIN NUMBER(5):=0;
 V_MAX NUMBER(5):=0;
 V_PROM NUMBER(9):=0;
 V_SUMA NUMBER(9):=0;
 V_CANTIDAD NUMBER(4):=0;
BEGIN
 SELECT MIN(SALARY),MAX(SALARY),SUM(SALARY),ROUND(AVG(SALARY)),COUNT(*) 
 INTO V_MIN,V_MAX,V_SUMA,V_PROM,V_CANTIDAD
 FROM EMPLOYEES;
 
 DBMS_OUTPUT.PUT_LINE('               INFORME DE LA EMPRESA             '||SYSDATE);
 DBMS_OUTPUT.PUT_LINE(RPAD(' ',15)||LPAD('-',42,'-'));
 DBMS_OUTPUT.PUT_LINE(RPAD('SALARIO MAXIMO',20)||RPAD('SALARIO PROMEDIO',20) ||
                      RPAD('SALARIO MINIMO',20)||RPAD('SALARIO TOTAL',20));
                      
 DBMS_OUTPUT.PUT_LINE(RPAD('-',80,'-'));
 DBMS_OUTPUT.PUT_LINE(RPAD(TO_CHAR(V_MAX,'$999,999'),20) || RPAD(TO_CHAR(V_PROM,'$999,999'),20) || 
                      RPAD(TO_CHAR(V_MIN,'$999,999'),20)|| RPAD(TO_CHAR(V_SUMA,'$999,999'),20));
 DBMS_OUTPUT.PUT_LINE(RPAD('-',80,'-'));
 DBMS_OUTPUT.PUT_LINE('LOS VALORES CALCULADOS ESTAN EFECTUADOS SOBRE '||V_CANTIDAD ||' EMPLEADOS');
END;

--2
DECLARE
V_DEPMAX VARCHAR(20);
V_EMPMAX NUMBER(5);
V_DEPMIN VARCHAR(20);
V_EMPMIN NUMBER(5);
BEGIN
SELECT DEPARTMENT_NAME,COUNT(*) INTO V_DEPMAX,V_EMPMAX FROM EMPLOYEES JOIN DEPARTMENTS USING(DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME
HAVING COUNT(*)=(SELECT MAX(COUNT(*)) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID);
SELECT DEPARTMENT_NAME,COUNT(*) INTO V_DEPMIN,V_EMPMIN FROM EMPLOYEES JOIN DEPARTMENTS USING(DEPARTMENT_ID)
WHERE ROWNUM=1
GROUP BY DEPARTMENT_NAME
HAVING COUNT(*)=(SELECT MIN(COUNT(*)) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID);
DBMS_OUTPUT.PUT_LINE(LPAD('INFORME PARA REDISTRIBUIR DEPARTAMENTOS',49));
DBMS_OUTPUT.PUT_LINE(LPAD(' ',10)||LPAD('-',39,'-'));
DBMS_OUTPUT.PUT_LINE('DEPARTAMENTO'||LPAD('TOTAL DE EMPLEADOS',40));
DBMS_OUTPUT.PUT_LINE(LPAD('-',52,'-'));
DBMS_OUTPUT.PUT_LINE(V_DEPMAX||LPAD(V_EMPMAX,36));
DBMS_OUTPUT.PUT_LINE(V_DEPMIN||LPAD(V_EMPMIN,30));
END;
--3
SELECT MAX(TRUNC((SYSDATE-HIRE_DATE)/365)) FROM EMPLOYEES;
SELECT FIRST_NAME ||' '|| LAST_NAME,SALARY,TRUNC((SYSDATE-HIRE_DATE)/365),
       (SALARY*TRUNC((SYSDATE-HIRE_DATE)/365))/100
FROM EMPLOYEES
WHERE TRUNC((SYSDATE-HIRE_DATE)/365) = (SELECT MAX(TRUNC((SYSDATE-HIRE_DATE)/365)) FROM EMPLOYEES);

DECLARE
 V_NOMBRE VARCHAR(30);
 V_SALARIO NUMBER(6);
 V_ANTIGUEDAD NUMBER(2);
 V_BONO NUMBER(5);
BEGIN
 SELECT FIRST_NAME ||' '|| LAST_NAME,SALARY,TRUNC((SYSDATE-HIRE_DATE)/365),
        (SALARY*TRUNC((SYSDATE-HIRE_DATE)/365))/100 INTO V_NOMBRE,V_SALARIO,V_ANTIGUEDAD,V_BONO
 FROM EMPLOYEES
 WHERE TRUNC((SYSDATE-HIRE_DATE)/365) = (SELECT MAX(TRUNC((SYSDATE-HIRE_DATE)/365)) FROM EMPLOYEES);
 DBMS_OUTPUT.PUT_LINE(LPAD('INFORME PAGO BONO POR ANTIGUEDAD',50));
 DBMS_OUTPUT.PUT_LINE(LPAD('--------------------------------',50));
 DBMS_OUTPUT.PUT_LINE('');
 DBMS_OUTPUT.PUT_LINE(RPAD('EMPLEAD0',20) || RPAD('AÑOS TRABAJADOS',20)||RPAD('SALARIO ACTUAL',20)||RPAD('VALOR BONO',20));
 DBMS_OUTPUT.PUT_LINE(RPAD('-',70,'-'));
 DBMS_OUTPUT.PUT_LINE(RPAD(V_NOMBRE,20) || RPAD(V_ANTIGUEDAD,20)||RPAD(TO_CHAR(V_SALARIO,'$999,999'),20)||RPAD(TO_CHAR(V_BONO,'$999,999'),20));
END;

--4
SELECT (MAX(COUNT(*))) FROM EMPLOYEES GROUP BY MANAGER_ID;
SELECT MANAGER_ID,COUNT(*) FROM EMPLOYEES GROUP BY MANAGER_ID
HAVING COUNT(*)=(SELECT (MAX(COUNT(*))) FROM EMPLOYEES GROUP BY MANAGER_ID);

DECLARE
 V_ID NUMBER(3);
 V_NOMBRE VARCHAR(30);
 V_EMPLEADOS NUMBER(2);
 V_ASIGNACION NUMBER(5);
BEGIN
 SELECT MANAGER_ID,COUNT(*) INTO V_ID,V_EMPLEADOS FROM EMPLOYEES GROUP BY MANAGER_ID
 HAVING COUNT(*)=(SELECT (MAX(COUNT(*))) FROM EMPLOYEES GROUP BY MANAGER_ID);
 SELECT FIRST_NAME||' '||LAST_NAME INTO V_NOMBRE FROM EMPLOYEES
 WHERE EMPLOYEE_ID=V_ID;
 V_ASIGNACION:=V_EMPLEADOS*1000;
 DBMS_OUTPUT.PUT_LINE(LPAD('INFORME PAGO ASIGNACION JEFE CON MAS EMPLEADO',55));
 DBMS_OUTPUT.PUT_LINE(RPAD(' ',10)||LPAD('-',45,'-'));
 DBMS_OUTPUT.PUT_LINE('ID.JEFE: '||V_ID ||'  NOMBRE:'||V_NOMBRE);
 DBMS_OUTPUT.PUT_LINE('');
 DBMS_OUTPUT.PUT_LINE(RPAD('EMPLEADOS A SU CARGO',30)||RPAD('VALOR ASIGNACION',30));
 DBMS_OUTPUT.PUT_LINE(LPAD('-',46,'-'));
 DBMS_OUTPUT.PUT_LINE(LPAD(V_EMPLEADOS,20)||LPAD(V_ASIGNACION,26));
END;
