select * from ventas;
select * from detalle_ventas;
select * from EMPLEADOS;
select * from CARGOS;
SELECT * FROM PRODUCTOS;

DECLARE
  CURSOR DESC_VENTAS IS
    SELECT v.NUMERO_DOCUMENTO "NUMERO_DOCUMENTO",SUM(d.PRECIO_UNITARIO*D.CANTIDAD*(1-D.DESCUENTO)) "NETO",
    ROUND(SUM(d.PRECIO_UNITARIO*D.CANTIDAD*(1-D.DESCUENTO))*0.19) "IVA",SUM(d.PRECIO_UNITARIO*D.CANTIDAD*(1-D.DESCUENTO))
    +ROUND(SUM(d.PRECIO_UNITARIO*D.CANTIDAD*(1-D.DESCUENTO))*0.19) "TOTAL"
    FROM DETALLE_VENTAS d
    JOIN VENTAS v ON(d.VENTA_ID = v.VENTA_ID)
    GROUP BY NUMERO_DOCUMENTO ORDER BY v.NUMERO_DOCUMENTO ASC; 
BEGIN
  FOR datos IN DESC_VENTAS
  LOOP
      DBMS_OUTPUT.PUT_LINE('La venta con Nro Docto: '||datos.NUMERO_DOCUMENTO||' tuvo el sgte detalle:');
      DBMS_OUTPUT.PUT_LINE(RPAD('Neto: ',10)||TO_CHAR(datos.neto,'$9,999,999'));
      DBMS_OUTPUT.PUT_LINE(RPAD('Iva: ',10)||TO_CHAR(datos.iva,'$9,999,999'));
      DBMS_OUTPUT.PUT_LINE(RPAD('TOTAL ',10)||TO_CHAR(datos.total,'$9,999,999'));
      DBMS_OUTPUT.PUT_LINE(RPAD('-',50,'-'));
  END LOOP;  
END;
--2
DECLARE
 CURSOR VENTAS IS
   SELECT e.NOMBRE||' '||e.APPATERNO "NOMBRE",NVL(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-D.DESCUENTO)),0) "NETO",NVL(SUM((d.PRECIO_UNITARIO*d.CANTIDAD*(1-D.DESCUENTO))*0.05),0) "COMISION"
   FROM EMPLEADOS e
   LEFT OUTER JOIN VENTAS v ON(v.VENDEDOR_ID=e.EMPLEADO_ID)
   LEFT OUTER JOIN DETALLE_VENTAS d ON(v.VENTA_ID = d.VENTA_ID)
   WHERE e.CARGO_ID=1
   GROUP BY e.NOMBRE,e.APPATERNO;
BEGIN
 FOR datos IN VENTAS
   LOOP
   DBMS_OUTPUT.PUT_LINE('El vendedor '||datos.NOMBRE);
   DBMS_OUTPUT.PUT_LINE('ventas netas: '||datos.neto);
   DBMS_OUTPUT.PUT_LINE('comision: '||datos.comision);
   DBMS_OUTPUT.PUT_LINE(RPAD('-',50,'-'));
   END LOOP;
END;
--3
DECLARE
CURSOR DESC_SUELDO IS
SELECT e.NOMBRE||' '||e.APPATERNO "NOMBRE",c.NOMBRE "CARGO",e.SUELDO_BASE "SUELDO",
ROUND(e.SUELDO_BASE+NVL(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)),0)*0.05) "SUELDO_IMPONIBLE",
ROUND(e.SUELDO_BASE+NVL(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)),0)*0.05) "COMISION",
ROUND((e.SUELDO_BASE+NVL(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)),0)*0.05)*0.10) "AFP",
ROUND((e.SUELDO_BASE+NVL(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)),0)*0.05)*0.07) "SALUD",
ROUND((e.SUELDO_BASE+NVL(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)),0)*0.05)*0.10+
(e.SUELDO_BASE+NVL(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)),0)*0.05)*0.07) "TOTAL_DESCUENTOS",
ROUND((e.SUELDO_BASE+NVL(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)),0)*0.05)-
((e.SUELDO_BASE+NVL(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)),0)*0.05)*0.10+
(e.SUELDO_BASE+NVL(SUM(d.PRECIO_UNITARIO*d.CANTIDAD*(1-d.DESCUENTO)),0)*0.05)*0.07)) "TOTAL"
FROM EMPLEADOS e
JOIN CARGOS c ON (e.CARGO_ID=c.CARGO_ID)
LEFT OUTER JOIN VENTAS v ON(e.EMPLEADO_ID=v.VENDEDOR_ID)
LEFT OUTER JOIN DETALLE_VENTAS d ON(v.VENTA_ID=d.VENTA_ID)
GROUP BY e.NOMBRE,e.APPATERNO,c.NOMBRE,e.SUELDO_BASE;
BEGIN
 FOR datos IN DESC_SUELDO
  LOOP
  DBMS_OUTPUT.PUT_LINE('El '||datos.cargo||' '||datos.nombre||':');
  DBMS_OUTPUT.PUT_LINE(RPAD('Sueldo Base: ',40)||datos.sueldo);
  DBMS_OUTPUT.PUT_LINE(RPAD('Comision: ',40)||datos.comision);
  DBMS_OUTPUT.PUT_LINE(LPAD('-',15,'-'));
  DBMS_OUTPUT.PUT_LINE(RPAD('Sueldo Imponible: ',40)||datos.sueldo_imponible);
  DBMS_OUTPUT.PUT_LINE(' ');
  DBMS_OUTPUT.PUT_LINE(RPAD('AFP: ',40)||datos.afp);
  DBMS_OUTPUT.PUT_LINE(RPAD('SALUD: ',40)||datos.salud);
  DBMS_OUTPUT.PUT_LINE(LPAD('-',15,'-'));
  DBMS_OUTPUT.PUT_LINE(RPAD('TOTAL DCTOS: ',40)||datos.total_descuentos);
  DBMS_OUTPUT.PUT_LINE(LPAD('=',50,'='));
  DBMS_OUTPUT.PUT_LINE(RPAD('TOTAL:',40)||datos.total);
  DBMS_OUTPUT.PUT_LINE(LPAD('/',50,'/'));
  DBMS_OUTPUT.PUT_LINE(LPAD('/',50,'/'));
  END LOOP;
END;