-- GUIA N°1 --

--1
SELECT * FROM EMPLOYEES WHERE NVL(MANAGER_ID,0) = 0;

SET SERVEROUTPUT ON; --MANDA LAS SALIDAS DE DBMS A LA SALIDA DE SCRIPT
DECLARE
 V_FECHA EMPLOYEES.HIRE_DATE%TYPE; -- HACE LA VARIABLE V_FECHA DEL MISMO TIPO QUE HIRE_DATE
 V_NOMBRE VARCHAR(30);
BEGIN
 SELECT FIRST_NAME ||' '||LAST_NAME,HIRE_DATE INTO V_NOMBRE,V_FECHA
 FROM EMPLOYEES WHERE NVL(MANAGER_ID,0) = 0;
 DBMS_OUTPUT.PUT_LINE('EL EMPLEADO ' || V_NOMBRE||'FUE CONTRATADO EL ' || TO_CHAR(V_FECHA,'DD "DE" MONTH "DEL AÑO" YYYY'));
END;

--2
DECLARE
 V_TOTAL NUMBER(3):=0;
 V_DEPTO VARCHAR(30);
BEGIN
 SELECT DEPARTMENT_NAME,COUNT(*) INTO V_DEPTO,V_TOTAL FROM EMPLOYEES 
 JOIN DEPARTMENTS USING(DEPARTMENT_ID)
 WHERE DEPARTMENT_ID = 50
 GROUP BY DEPARTMENT_NAME;
 DBMS_OUTPUT.PUT_LINE('EN EL DEPARTAMENTO '||V_DEPTO||' TRABAJAN' || V_TOTAL ||' EMPLEADOS');
END;

--3
DECLARE
 V_NOMBRE VARCHAR(30);
BEGIN
 SELECT FIRST_NAME ||' '|| LAST_NAME INTO V_NOMBRE FROM EMPLOYEES
 WHERE SALARY =(SELECT MIN(SALARY) FROM EMPLOYEES);
 DBMS_OUTPUT.PUT_LINE('EL EMPLEADO '||V_NOMBRE||' ES EL EMPLEADO CON EL SALARIO MAS BAJO');
END;

--4
DECLARE
 V_COMISION NUMBER(3):=0;
BEGIN
 SELECT ROUND(AVG(SALARY*NVL(COMMISSION_PCT,0))) INTO V_COMISION 
 FROM EMPLOYEES;
 DBMS_OUTPUT.PUT_LINE('EL PROMEDIO DE COMISION ES '||TO_CHAR(V_COMISION,'$999,999'));
END;

--5                                        
DECLARE
 V_ID NUMBER(3):=0;
 V_NOMBRE VARCHAR(30);
 V_MANAGER NUMBER(3):=0;
 V_UBICACION NUMBER(4):=0;
BEGIN
 SELECT DEPARTMENT_ID INTO V_ID FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID HAVING COUNT(*)=(SELECT MAX(COUNT(EMPLOYEE_ID))FROM EMPLOYEES
                                        GROUP BY DEPARTMENT_ID);
 SELECT DEPARTMENT_NAME,LOCATION_ID,MANAGER_ID INTO V_NOMBRE,V_UBICACION,V_MANAGER
 FROM DEPARTMENTS WHERE DEPARTMENT_ID=V_ID;
 DBMS_OUTPUT.PUT_LINE('LA INFORMACION DE DEPTO CON MAYOR NUMERO DE EMPLEADOS ES');
 DBMS_OUTPUT.PUT_LINE('IDENTIFICACION: ' || V_ID);
 DBMS_OUTPUT.PUT_LINE('NOMBRE: '||V_NOMBRE);
 DBMS_OUTPUT.PUT_LINE('JEFE: '||V_MANAGER);
 DBMS_OUTPUT.PUT_LINE('UBIACION: '||V_UBICACION);
END;

--6
DECLARE
 V_NOMBRE VARCHAR(30);
 V_SALARIO NUMBER(7):=0;
 V_BONO NUMBER(3):=0;
BEGIN
 SELECT FIRST_NAME ||' '|| LAST_NAME,SALARY,SALARY*TRUNC(SALARY/1000)/100
 INTO V_NOMBRE,V_SALARIO,V_BONO
 FROM EMPLOYEES WHERE SALARY=(SELECT MIN(SALARY) FROM EMPLOYEES);
 DBMS_OUTPUT.PUT_LINE('EL SALARIO DEL EMPLEADO '||V_NOMBRE ||' ES DE: '|| TO_CHAR(V_SALARIO,'$999,999'));
 DBMS_OUTPUT.PUT_LINE('POR LO TANTO SU BONO ES DE: '|| TO_CHAR(V_BONO,'$999,999'));
END;

--7
/*
EL BANCO NECESITA SABER CUAL ES EL DEPARTAMENTO CON EL MAYOR Y MENOR NUMERO DE EMPLEADOS
*/
SELECT DEPARTMENT_ID FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID HAVING COUNT(*)=(SELECT MAX(COUNT(EMPLOYEE_ID))FROM EMPLOYEES
                                        GROUP BY DEPARTMENT_ID);
SELECT * FROM(
SELECT DEPARTMENT_ID FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID HAVING COUNT(*)=(SELECT MIN(COUNT(EMPLOYEE_ID))FROM EMPLOYEES
                                        GROUP BY DEPARTMENT_ID ) AND NVL(DEPARTMENT_ID,0)!=0
                                        ) WHERE ROWNUM = 1;
DECLARE 
V_IDMAX NUMBER(3):=0;
V_IDMIN NUMBER(3):=0;
BEGIN
SELECT * FROM(
SELECT DEPARTMENT_ID INTO V_IDMIN FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID HAVING COUNT(*)=(SELECT MIN(COUNT(EMPLOYEE_ID))FROM EMPLOYEES
                                        GROUP BY DEPARTMENT_ID ) AND NVL(DEPARTMENT_ID,0)!=0
                                        ) WHERE ROWNUM = 1;
SELECT DEPARTMENT_ID INTO V_IDMAX FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID HAVING COUNT(*)=(SELECT MAX(COUNT(EMPLOYEE_ID))FROM EMPLOYEES
                                        GROUP BY DEPARTMENT_ID);
DBMS_OUTPUT.PUT_LINE('EL SALARIO DEL EMPLEADO '||V_NOMBRE ||' ES DE: '|| TO_CHAR(V_SALARIO,'$999,999'));                                        
END;
                                        
                                      



