SELECT * FROM FACTURA;
SELECT * FROM HABITACION;
SELECT * FROM RECEPCIONISTA;
SELECT * FROM CLIENTE;
SELECT * FROM RESERVA ORDER BY ID_RESERVA ASC;



--1
SELECT COUNT(*) "CANTIDAD DE CLIENTES",MOTIVO,ROUND(AVG(CANT_DIAS)) "PROMEDIO DE DIAS ALOJADOS"FROM RESERVA 
WHERE MOTIVO='Arriendo' GROUP BY MOTIVO;

--2
SELECT  'El Cliente ' ||CONCAT(CNOMBRE,' '||CAPELLIDO)|| ' a realizado '||COUNT(ID_RESERVA)||' reservas' "INFORMACION "
FROM RESERVA JOIN CLIENTE USING(ID_CLIENTE) GROUP BY CNOMBRE,CAPELLIDO 
ORDER BY COUNT(ID_RESERVA) DESC ;

--3
SELECT CONCAT(RNOMBRE,' '||RAPELLIDO) "NOMBRE RECEPCIONISTA",TO_CHAR(SUELDO,'$99,999') SUELDO,TO_CHAR(FECHA_CONTRATO,'DD/MM/YYYY') "FECHA CONTRATO",
TRUNC((SYSDATE-FECHA_CONTRATO)/365) AÑOS_TRABAJADOS,TO_CHAR(ROUND(((SYSDATE-FECHA_CONTRATO)/365)*SUELDO)/100,'$999,999') "AUMENTO",
TO_CHAR(ROUND((((SYSDATE-FECHA_CONTRATO)/365)*SUELDO)/100)+SUELDO,'$999,999')"SUELDO AUMENTADO"
FROM RECEPCIONISTA;

--4
SELECT CONCAT(RNOMBRE,' '||RAPELLIDO) "NOMBRE RECEPCIONISTA",RUT,COUNT(ID_RESERVA) "CLIENTES ATENDIDOS"
FROM RECEPCIONISTA LEFT OUTER JOIN RESERVA USING(ID_RECEPCIONISTA)
GROUP BY RNOMBRE,RAPELLIDO,RUT HAVING COUNT(ID_RESERVA)=0;

--5
CREATE OR REPLACE VIEW V_INFO_RESERVAS
AS SELECT NRO_HABITACION,FECHA_RESERVA,MOTIVO,SERV_HABITACION
FROM RESERVA JOIN HABITACION USING(NRO_HABITACION) 
ORDER BY NRO_HABITACION,FECHA_RESERVA ASC;
SELECT * FROM V_INFO_RESERVAS;

--6
SELECT TIPO_HABITACION,TO_CHAR(SUM(COSTO),'$9,999,999') GANANCIA_TOTAL 
FROM HABITACION 
GROUP BY TIPO_HABITACION;

--7
SELECT 'El cliente '||CONCAT(CNOMBRE,' '||CAPELLIDO)||' fue atendido por ' ||CONCAT(RNOMBRE,' '||RAPELLIDO)||' durante ' ||COUNT(*)|| ' reservas en el mes de Marzo' "DETALLES"
FROM CLIENTE  JOIN RESERVA USING(ID_CLIENTE) JOIN RECEPCIONISTA USING(ID_RECEPCIONISTA)
WHERE extract(month from FECHA_RESERVA) = 3
GROUP BY CNOMBRE,CAPELLIDO,RNOMBRE,RAPELLIDO;

--8
SELECT CONCAT(CNOMBRE,' '||CAPELLIDO) NOMBRE_CLIENTE,ESTADO "ESTADO DE PAGO",CANT_DIAS "CANTIDAD DE DIAS HOSPEDADO",TO_CHAR(COSTO,'$999,999') "PRECIO ACTUAL X DIA",
TO_CHAR(ROUND((COSTO*CANT_DIAS)/100),'$999,999') AUMENTO,TO_CHAR(ROUND(((COSTO*CANT_DIAS)/100)+COSTO),'$9,999,999') PRECIO_FINAL FROM CLIENTE
JOIN RESERVA USING(ID_CLIENTE) JOIN FACTURA USING(NRO_FACTURA) JOIN HABITACION USING(NRO_HABITACION)
WHERE ESTADO ='Pendiente';

--9
SELECT HORARIO,COUNT(ID_RESERVA) "CANTIDAD DE RESERVAS ATENDIDAD"
FROM RECEPCIONISTA JOIN RESERVA USING(ID_RECEPCIONISTA)
GROUP BY HORARIO 
ORDER BY COUNT(ID_RESERVA) DESC;

--10
CREATE OR REPLACE VIEW V_TODO_RECEP
AS SELECT CONCAT(RNOMBRE,' '||RAPELLIDO) NOMBRE_RECEPCIONISTA,RUT,TO_CHAR(FECHA_CONTRATO,'dd" de "Month" del "YYYY') FECHA_CONTRATO,
ROUND((SYSDATE-FECHA_CONTRATO)/365) AÑOS_CONTRATADO,ROUND((SYSDATE-FECHA_CONTRATO)/12) MESES_CONTRATADO,ROUND(SYSDATE-FECHA_CONTRATO) DIAS_CONTRATADO
FROM RECEPCIONISTA;
SELECT * FROM V_TODO_RECEP;

--11

SELECT c.ID_CLIENTE,c.CNOMBRE||' '||c.CAPELLIDO "CLIENTE",SUM(h.COSTO) "MONTO TOTAL" FROM CLIENTE c 
JOIN RESERVA r ON (c.ID_CLIENTE = r.ID_CLIENTE)
JOIN HABITACION h ON (r.NRO_HABITACION = h.NRO_HABITACION)
GROUP BY c.ID_CLIENTE,c.CNOMBRE, c.CAPELLIDO
ORDER BY c.ID_CLIENTE,SUM(h.COSTO) ASC;

--12
SELECT c.CNOMBRE||' '||c.CAPELLIDO "CLIENTE",r.NRO_HABITACION,r.CANT_DIAS,
ROUND(r.CANT_DIAS/2) "PORCENTAJE DESCUENTO",TO_CHAR(h.COSTO,'$99,999,999') "COSTO", TO_CHAR(h.COSTO-h.COSTO*(ROUND(r.CANT_DIAS/2)/100),'$99,999,999') "COSTO FINAL" FROM CLIENTE c 
JOIN RESERVA r ON (c.ID_CLIENTE = r.ID_CLIENTE)
JOIN HABITACION h ON (r.NRO_HABITACION = h.NRO_HABITACION)
WHERE r.NRO_HABITACION=21;

--13
SELECT rp.RNOMBRE||' '||rp.RAPELLIDO "NOMBRE",COUNT(r.ID_RESERVA) "RESERVAS",COUNT(r.ID_RESERVA)*2500 "BONO",TO_CHAR(rp.SUELDO,'$99,999,999') "SUELDO",
TO_CHAR((COUNT(r.ID_RESERVA)*2500)+rp.SUELDO,'$99,999,999') "SUELDO MAS BONIFICACION"
FROM RECEPCIONISTA rp
LEFT OUTER JOIN RESERVA r ON(rp.ID_RECEPCIONISTA = r.ID_RECEPCIONISTA)
GROUP BY rp.RNOMBRE,rp.RAPELLIDO,rp.SUELDO
ORDER BY "SUELDO MAS BONIFICACION" DESC;

--14
SELECT h.TIPO_HABITACION,COUNT(r.NRO_HABITACION) "NUMERO DE RESERVAS" FROM HABITACION h 
JOIN RESERVA r ON(h.NRO_HABITACION = r.NRO_HABITACION)
GROUP BY h.TIPO_HABITACION HAVING COUNT(r.NRO_HABITACION)<4;

--15
SELECT c.CNOMBRE||' '||c.CAPELLIDO "NOMBRE",COUNT(r.ID_RESERVA)"RESERVAS" FROM CLIENTE c
JOIN RESERVA r ON(c.ID_CLIENTE=r.ID_CLIENTE)
GROUP BY c.CNOMBRE,c.CAPELLIDO 
HAVING (SELECT MAX(COUNT(r.ID_RESERVA)) FROM CLIENTE c
JOIN RESERVA r ON(c.ID_CLIENTE=r.ID_CLIENTE)
GROUP BY c.ID_CLIENTE)=COUNT(r.ID_RESERVA);