--a)
CREATE OR REPLACE PACKAGE PKG_SUELDO IS
 v_sueldo_final NUMBER;
 FUNCTION FN_SUELDO_FINAL(RUT VARCHAR2,FECHA DATE) RETURN NUMBER;
END PKG_SUELDO;

CREATE OR REPLACE PACKAGE BODY PKG_SUELDO IS
 FUNCTION FN_SUELDO_FINAL(RUT VARCHAR,FECHA DATE) RETURN NUMBER IS
 BEGIN
  SELECT SUE_MONTO_BASE+SUE_COMISION-(SUE_MONTO_BASE+SUE_COMISION+SUE_BONO)*0.07-(SUE_MONTO_BASE+SUE_COMISION+SUE_BONO)*0.10
  INTO v_sueldo_final FROM SUELDOS
  WHERE EJE_RUT=RUT AND EXTRACT(MONTH FROM SUE_PERIODO)=EXTRACT (MONTH FROM FECHA);
  RETURN v_sueldo_final;
 END FN_SUELDO_FINAL;
END PKG_SUELDO;

--b)
CREATE OR REPLACE FUNCTION F_ISAPRE(RUT VARCHAR2,FECHA DATE)
RETURN NUMBER
IS 
ISAPRE NUMBER;
BEGIN
SELECT (SUE_MONTO_BASE+SUE_COMISION+SUE_BONO)*0.07 ISAPRER INTO ISAPRE FROM SUELDOS WHERE EJE_RUT = RUT AND TO_CHAR(SUE_PERIODO,'DD/MM/YYYY')=FECHA AND
SUE_PERIODO BETWEEN TO_DATE('01/01/2016', 'dd/mm/yyyy') AND TO_DATE('01/02/2016', 'dd/mm/yyyy');
RETURN ISAPRE;
END F_ISAPRE;

CREATE OR REPLACE FUNCTION F_AFP(RUT VARCHAR2,FECHA DATE)
RETURN NUMBER
IS 
v_afp NUMBER;
BEGIN
SELECT (SUE_MONTO_BASE+SUE_COMISION+SUE_BONO)*0.10 INTO v_afp FROM SUELDOS WHERE EJE_RUT = RUT AND TO_CHAR(SUE_PERIODO,'DD/MM/YYYY')=FECHA AND
SUE_PERIODO BETWEEN TO_DATE('01/01/2016', 'dd/mm/yyyy') AND TO_DATE('01/02/2016', 'dd/mm/yyyy');
RETURN v_afp;
END F_AFP;

DECLARE
v_isapre NUMBER;
v_afp NUMBER;
BEGIN
DBMS_OUTPUT.PUT_LINE('---PROBANDO---');
v_isapre:=F_ISAPRE('18936554',TO_DATE('01/01/2016', 'dd/mm/yyyy'));
v_afp:=F_AFP('18936554',TO_DATE('01/01/2016', 'dd/mm/yyyy'));
DBMS_OUTPUT.PUT_LINE(v_isapre);
DBMS_OUTPUT.PUT_LINE(v_afp);
END;