
CREATE TABLE REGISTRO_ERROR
(
  id_error INTEGER NOT NULL,
  nom_subprograma VARCHAR2 (1000) NOT NULL,
  error_mensaje VARCHAR2 (1000) NOT NULL
);
ALTER TABLE REGISTRO_ERROR ADD CONSTRAINT REGISTRO_ERROR_PK PRIMARY KEY(id_error);

SELECT * FROM REGISTRO_ERROR;
CREATE SEQUENCE SEQ_ID_ERROR;
CREATE OR REPLACE TRIGGER TRG_RESTRINGE_FECHA
BEFORE INSERT OR UPDATE OR DELETE ON PAGO_EJECUTIVOS

BEGIN

END;