SELECT * FROM EMPLOYEES;

--1)

SELECT CONCAT(FIRST_NAME,' '||LAST_NAME) AS "EMPLEADO",NVL(TO_CHAR(MANAGER_ID),'No posee jefe') AS "JEFE" FROM EMPLOYEES ORDER BY JEFE DESC;

--2)

SELECT EMPLOYEE_ID "EMPLEADO",SALARY "SALARIO", TRUNC(SALARY/1000) "PORCENTAJE DE MOVILIZACION" FROM EMPLOYEES;

--3)

SELECT FIRST_NAME "NOMBRE", LAST_NAME "APELLIDO", JOB_ID "TRABAJO", CONCAT(SUBSTR(FIRST_NAME,1,3),JOB_ID) "NOMBRE_USUARIO", 
UPPER(CONCAT(TO_CHAR(HIRE_DATE,'ddyyyy'),SUBSTR(LAST_NAME,-2))) "CLAVE USUARIO" FROM EMPLOYEES ORDER BY LAST_NAME ASC;

--4)

SELECT RPAD(FIRST_NAME,15)||'posee un salario de'||LPAD(SALARY,10) "LISTADO DE SALARIOS" FROM EMPLOYEES;

--5)

SELECT 'el empleado '||FIRST_NAME||' '||LAST_NAME||' fue contratado el '||TO_CHAR(HIRE_DATE,'dd " de " month " del " yyyy') "CONTRATOS" 
FROM EMPLOYEES ORDER BY HIRE_DATE ASC;

--6)

SELECT 'el empleado '||LAST_NAME||' posee un salario mensual de '||TO_CHAR(SALARY,'$99999.00')||' pero su sueño es ganar '||
TO_CHAR(SALARY*3,'$99999.00') "Salario Soñado" FROM EMPLOYEES WHERE MANAGER_ID>0;

--7)

SELECT EMPLOYEE_ID "EMPLEADO", DEPARTMENT_ID "DEPARTAMENTO", SALARY "SALARIO",ROUND(SALARY*0.258) "REAJUSTE", ROUND(SALARY*0.258)+SALARY "SALARIO REAJUSTADO" FROM EMPLOYEES WHERE SALARY<5000 ORDER BY DEPARTMENT_ID ASC;

--8)

SELECT FIRST_NAME||' '||LAST_NAME "EMPLEADO",JOB_ID "TRABAJO QUE DESEMPEÑO",
DECODE(JOB_ID,'AD_PRES','A','ST_MAN','B','IT_PROG','C','SA_REP','D','ST_CLERK','E','O') 
"GRADO SEGUN SU TRABAJO" FROM EMPLOYEES ORDER BY LAST_NAME ASC;

--9)
--a)
SELECT CONCAT(FIRST_NAME,' '||LAST_NAME) "EMPLEADO", TO_CHAR(SALARY,'$99,999') "SALARIO", TO_CHAR(SUBSTR(SALARY,1,1)/100*SALARY,'$999') "REAJUSTE" FROM EMPLOYEES;

--b)
SELECT EMPLOYEE_ID "ID_EMPLEADO",SALARY "SALARIO SIN COMISION",NVL(COMMISSION_PCT,0) "COMISION", NVL(SALARY*COMMISSION_PCT,0) "VALOR COMISION", NVL(SALARY*COMMISSION_PCT,0)+SALARY "SALARIO TOTAL" FROM EMPLOYEES;

--c}
SELECT EMPLOYEE_ID "ID_EMPLEADO", TO_CHAR(HIRE_DATE,'dd/mm/yyyy') "FECHA DE CONTRATO",SALARY "SALARIO",
TO_CHAR(SYSDATE,'yyyy')-TO_CHAR(HIRE_DATE, 'yyyy') "AÑOS DE CONTRATO",((TO_CHAR(SYSDATE,'yyyy')-TO_CHAR(HIRE_DATE, 'yyyy'))/100)*SALARY 
"AUMENTO" FROM EMPLOYEES ORDER BY "AÑOS DE CONTRATO" DESC;