SELECT * FROM EMPLOYEES;
--1--
SELECT MAX(SALARY) "SALARIO MAXIMO",MIN(SALARY) "SALARIO MINIMO", SUM(SALARY) "SUMATORIA DE SALARIO", ROUND(AVG(SALARY)) "SALARIO PROMEDIO" FROM EMPLOYEES;

--2--
SELECT JOB_ID "TRABAJO", MAX(SALARY) "SALARIO MAXIMO",MIN(SALARY) "SALARIO MINIMO", SUM(SALARY) "SUMATORIA DE SALARIO", 
ROUND(AVG(SALARY)) "SALARIO PROMEDIO" FROM EMPLOYEES GROUP BY JOB_ID ORDER BY JOB_ID ASC;

--3--
--a)--
SELECT JOB_ID "TRABAJO", COUNT(*) "TOTAL EMPLEADOS" FROM EMPLOYEES GROUP BY JOB_ID;

--b)--
SELECT NVL(TO_CHAR(MANAGER_ID),' ') "JEFE",COUNT(EMPLOYEE_ID) "TOTAL DE EMPLEADOS A SU CARGO" FROM EMPLOYEES GROUP BY MANAGER_ID ORDER BY "TOTAL DE EMPLEADOS A SU CARGO" DESC, MANAGER_ID ASC;

--c)
SELECT NVL(TO_CHAR(DEPARTMENT_ID),' ') "DEPARTAMENTO",COUNT(*) "TOTAL DE EMPLEADOS",SUM(SALARY) "SALARIO TOTAL POR DEPTO" FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID ASC;

--d)
SELECT TO_CHAR(MAX(SALARY)-MIN(SALARY), '$99999') "DIFERENCIA" FROM EMPLOYEES;

--e)
SELECT COUNT(AVG(NVL(MANAGER_ID,1))) "DISTINTOS JEFES" FROM EMPLOYEES GROUP  BY MANAGER_ID;

--f)--
SELECT DEPARTMENT_ID "DEPARTAMENTO", COUNT(EMPLOYEE_ID) "TOTAL DE MEPLEADOS" FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING COUNT(EMPLOYEE_ID)>5;

--g)--
SELECT DEPARTMENT_ID, JOB_ID, MIN(SALARY) FROM EMPLOYEES  WHERE SALARY>6000 AND DEPARTMENT_ID>0 GROUP BY DEPARTMENT_ID,JOB_ID ORDER BY DEPARTMENT_ID,JOB_ID ASC;

--4--
--a)--
SELECT DEPARTMENT_ID,COUNT(*),SUM(SALARY) "SALARIO" FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING SUM(SALARY) BETWEEN 15000 AND 30000 ORDER BY "SALARIO" ASC;

--b)--
SELECT NVL(TO_CHAR(MANAGER_ID),' '),COUNT(*),MAX(SALARY),ROUND((COUNT(*)/100) * MAX(SALARY)) FROM EMPLOYEES GROUP BY MANAGER_ID ORDER BY MANAGER_ID ASC;

--c)--
SELECT JOB_ID "TRABAJO",NVL(TO_CHAR(DECODE(DEPARTMENT_ID,20,SUM(SALARY))),' ') "TOTAL DEPTO 20",NVL(TO_CHAR(DECODE(DEPARTMENT_ID,50,SUM(SALARY))),' ') 
"TOTAL DEPTO 50",NVL(TO_CHAR(DECODE(DEPARTMENT_ID,80,SUM(SALARY))),' ') "TOTAL DEPTO 80",NVL(TO_CHAR(DECODE(DEPARTMENT_ID,90,SUM(SALARY))),' ') "TOTAL DEPTO 90" 
FROM EMPLOYEES WHERE DEPARTMENT_ID IN(20,50,80,90)GROUP BY JOB_ID,DEPARTMENT_ID;





